export enum PermissionEnum{
    // user
    CREATE_USER = "CREATE_USER",
    READ_USER = "READ_USER",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",

    // lottery
    CREATE_LOTTERY = "CREATE_LOTTERY",
    READ_LOTTERY = "READ_LOTTERY",
    UPDATE_LOTTERY = "UPDATE_LOTTERY",
    DELETE_LOTTERY = "DELETE_LOTTERY",

    // permission
    CREATE_PERMISSION = "CREATE_PERMISSION",
    READ_PERMISSION = "READ_PERMISSION",
    UPDATE_PERMISSION = "UPDATE_PERMISSION",
    DELETE_PERMISSION = "DELETE_PERMISSION",

    // coin
    CREATE_COIN = "CREATE_COIN",
    READ_COIN = "READ_COIN",
    UPDATE_COIN = "UPDATE_COIN",
    DELETE_COIN = "DELETE_COIN",

    // favourite
    CREATE_FAVOURITE = "CREATE_FAVOURITE",
    READ_FAVOURITE = "READ_FAVOURITE",
    UPDATE_FAVOURITE = "UPDATE_FAVOURITE",
    DELETE_FAVOURITE = "DELETE_FAVOURITE",

    // prize
    CREATE_PRIZE = "CREATE_PRIZE",
    READ_PRIZE = "READ_PRIZE",
    UPDATE_PRIZE = "UPDATE_PRIZE",
    DELETE_PRIZE = "DELETE_PRIZE",
}